version: "3.8"

services:
  db:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: paw
      MARIADB_USER: test
      MARIADB_PASSWORD: password
    #      MYSQL_TCP_PORT: 3306
    #      MYSQL_UNIX_PORT: 3306
    ports:
      - "3311:3306"
    #    volumes:
    #      - ./database/ddl:/docker-entrypoint-initdb.d
    #      - ./database/data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "--silent",
          "-h",
          "localhost",
          "-u",
          "root",
          "-ppw",
        ]
      timeout: 20s
      retries: 10
