export enum Language {
  KOREAN = "KOREAN",
  ENGLISH = "ENGLISH",
  JAPANESE = "JAPANESE",
  SPANISH = "SPANISH",
  GERMAN = "GERMAN",
  FRENCH = "FRENCH",
  ITALIAN = "ITALIAN",
  PORTUGUESE = "PORTUGUESE",
}
