export enum NotificationType {
  NEW_FOLLOW = "NEW_FOLLOW",
  NEW_BOARD_COMMENT = "NEW_BOARD_COMMENT",
  NEW_COMMENT_TAG = "NEW_COMMENT_TAG",
  REACTION_TEN = "REACTION_TEN",
  REACTION_FORTY_TWO = "REACTION_FORTY_TWO",
  REACTION_ONE_HUNDRED = "REACTION_ONE_HUNDRED",
}
