export enum ReportReason {
  WRONG_ANIMAL_CATEGORY = "WRONG_ANIMAL_CATEGORY",
  INSULTS = "INSULTS",
  AD_SPAM = "AD_SPAM",
  INAPPROPRIATE_NICKNAME = "INAPPROPRIATE_NICKNAME",
  SEXUAL = "SEXUAL",
  VIOLENCE = "VIOLENCE",
  IRRELEVANT = "IRRELEVANT",
  ETC = "ETC",
}
